apiVersion: v1
kind: Service
metadata:
  name: easytravel-www
  labels:
    app: easytravel-k8s
    type: www-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: easytravel-k8s
    type: www-pod