apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  name: simplcommerce-ingress
spec:
  rules:
  - host: simplcommerce.3-8-18-100.nip.io
    http:
      paths:
      - backend:
          serviceName: simplcommerce
          servicePort: 80
        path: /
  tls:
  - hosts:
    - simplcommerce.3-8-18-100.nip.io
