apiVersion: v1
kind: Service
metadata:
  labels:
    app: simplcommerce
  name: simplcommerce
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: simplcommerce
  type: NodePort