apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
#echo "plain_value" | base64
#ET_MONGO_AUTH_DB: "admin"
  ET_MONGO_AUTH_DB: YWRtaW4K
#ET_DATABASE_USER: "etAdmin"
  ET_DATABASE_USER: ZXRBZG1pbgo=
#ET_DATABASE_PASSWORD: "adminadmin"
  ET_DATABASE_PASSWORD: YWRtaW5hZG1pbgo=