apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  CATALINA_OPTS: "-Dconfig.apmServerDefault=APM -Xmx525m -Djava.security.egd=file:/dev/./urandom"
  ET_BACKEND_URL: "http://easytravel-backend:8080"